See user location on map
SachaKor/SDP-PolyCrowd pull request #78
Opened 2020-03-29 12:54 UTC by Gianniii

2020-03-29 16:11 UTC, salimbeni1 approved these changes

2020-03-29 17:44 UTC, choelzl requested changes
If possible only merge tested code onto master. Avoiding it from breaking and requiring more work to debug later on.

2020-03-29 17:44 UTC, choelzl commented on app/build.gradle
> -
Please dont commit irelevant changes to files

2020-03-29 17:44 UTC, choelzl commented on app/src/main/res/layout/activity_main.xml
> -
Please dont commit irelevant changes to files

2020-03-29 17:44 UTC, choelzl commented on app/src/main/java/ch/epfl/polycrowd/map/MapActivity.java
> +        buttonRight.setOnClickListener(new View.OnClickListener() {
Lambda's would allow those 4-5 lines to be written as 1 line

2020-03-29 17:44 UTC, choelzl commented on app/src/main/java/ch/epfl/polycrowd/map/MapActivity.java
> +        buttonLeft.setOnClickListener(new View.OnClickListener() {
Lambda's would allow those 4-5 lines to be written as 1 line

2020-03-29 17:44 UTC, choelzl commented on app/src/main/java/ch/epfl/polycrowd/map/MapActivity.java
> +        buttonRight.setOnClickListener(new View.OnClickListener() {
Lambda's would allow those 4-5 lines to be written as 1 line

2020-03-29 17:44 UTC, choelzl commented on app/src/main/java/ch/epfl/polycrowd/map/MapActivity.java
> +        buttonLeft.setOnClickListener(new View.OnClickListener() {
Lambda's would allow those 4-5 lines to be written as 1 line

2020-03-29 17:44 UTC, choelzl commented on app/src/main/java/ch/epfl/polycrowd/map/MapActivity.java
> +        buttonRight.setOnClickListener(new View.OnClickListener() {
Lambda's would allow those 4-5 lines to be written as 1 line

2020-03-29 17:44 UTC, choelzl commented on app/src/main/java/ch/epfl/polycrowd/map/MapActivity.java
> +        buttonLeft.setOnClickListener(new View.OnClickListener() {
Lambda's would allow those 4-5 lines to be written as 1 line

2020-03-30 09:42 UTC, choelzl approved these changes

2020-03-30 10:20 UTC, merged